services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  service-pg-docker:
    image: bitnami/postgresql
    container_name: dev-postgresql
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=game
    ports:
      - '5432:5432'
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge